[package]
name = "bryson-craft"
version = "1.1.0"
edition = "2024"

[dependencies]
bevy = "0.19.1"
bevy_voxel_world = "0.17.0"
encase_derive_impl = "=0.12.1"
image = "0.25.10"
noise = "0.9.0"
rand = "0.10.2"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
syn = "=2.0.119"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
zip = "8.6.0"
